modLoader="neoforge"
loaderVersion="[21,)"
license="MIT"
issueTrackerURL=""

[[mods]]
modId="origins"
version="${mod_version}"
displayName="Origins (NeoForge)"
description="Origins port for NeoForge 1.21.1"

[[dependencies.origins]]
modId="neoforge"
mandatory=true
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"
