modLoader = "javafml"
loaderVersion = "[7,)"
license = "MIT"
[[mods]]
modId = "origins"
version = "${mod_version}"
displayName = "Origins (NeoForge)"
authors = "Apace"
description = '''
An origins-style mod ported to NeoForge.
'''
[[dependencies.origins]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"
