modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="origins"
version="${mod_version}"
displayName="Origins (NeoForge)"
authors="Apace100, Contributors"
description='''
Origins: Live as a supernatural being with unique traits.
'''

[[dependencies.origins]]
modId="neoforge"
mandatory=true
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"
