modLoader="javafml"
loaderVersion="[2,)"
license="MIT"

[[mods]]
modId="origins"
version="${mod_version}"
displayName="Origins (NeoForge)"
description="A NeoForge port of the Origins mod."

[[dependencies.origins]]
    modId="neoforge"
    mandatory=true
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"
