modLoader="neoforge"
loaderVersion="[21,)"
license="MIT"
issueTrackerURL=""

[[mods]]
modId="${neoforge.mod.id}"
version="${neoforge.mod.version}"
displayName="Origins (NeoForge)"
description="Origins port for NeoForge ${neoforge.mod.mc}"

[[dependencies.${neoforge.mod.id}]]
modId="neoforge"
mandatory=true
versionRange="[21,)"
ordering="NONE"
side="BOTH"

[[dependencies.${neoforge.mod.id}]]
modId="minecraft"
mandatory=true
versionRange="[${neoforge.mod.mc},)"
ordering="NONE"
side="BOTH"
