modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="origins"
version="${mod_version}"
displayName="Origins (NeoForge)"
authors="Apace100, community"
description="NeoForge port of Origins."

[[dependencies.origins]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="BOTH"
