modLoader="javafml"
loaderVersion="[2,)"
license="MIT"

[[mods]]
modId="origins"
version="${mod_version}"
displayName="Origins"
authors="CyberDay1"
description="Forge → NeoForge port of Origins."

[[dependencies.origins]]
modId="neoforge"
type="required"
versionRange="[21.1.209,)"
ordering="NONE"
side="BOTH"

[[dependencies.origins]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.1]"
ordering="NONE"
side="BOTH"
