modLoader="javafml"
loaderVersion="[2,)"
license="MIT"

[[mods]]
modId="tectonicexpanded"
version="${mod_version}"
displayName="Tectonic Expanded"
description="Expanded tectonic worldgen"
authors="CyberDay1"

[[dependencies.origins]]
modId="neoforge"
type="required"
versionRange="[21.1.209,)"
ordering="NONE"
side="BOTH"

[[dependencies.origins]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.1]"
ordering="NONE"
side="BOTH"
