name: Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Compile with strict lint and warnings
        run: ./gradlew clean build --warning-mode all --console=plain --stacktrace

      - name: Run Mixin Compatibility Validation
        run: ./gradlew validateMixinCompatLevel

      - name: Run Placeholder Guard
        run: python3 scripts/assert-no-placeholders.py

      - name: Upload Problems Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-problems-report
          path: build/reports/problems/problems-report.html
          if-no-files-found: warn
