name: Build (Stonecutter Matrix)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate-wrapper:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2

  build:
    name: Build ${{ matrix.variant }}
    runs-on: ubuntu-latest
    needs: validate-wrapper
    strategy:
      fail-fast: false
      matrix:
        variant: [ "1.21.1-neoforge", "1.21.5-neoforge", "1.21.10-neoforge" ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Select Stonecutter variant
        run: ./gradlew --no-daemon stonecutter use ${{ matrix.variant }}

      - name: Build
        run: ./gradlew --no-daemon --no-parallel clean build

      - name: Print versions
        run: ./gradlew --no-daemon printVersions || true

      - name: Cache Gradle wrapper and caches
        if: always()
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'stonecutter.json') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
